[project]
name = "docflow-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SOUMOJIT-CHAKRABORTY", email = "goutamghambir2018@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "psycopg>=3.3.6",
    "sqlalchemy>=2.1.3",
]

[project.scripts]
docflow-ai = "docflow_ai:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
